app.py
from flask import Flask
from routes.rutas import home

app = Flask(__name__)
app.register_blueprint(home)

main.py
from app import app

app.run(debug=True)

routes/rutas.py
from flask import Blueprint, render_template, request

home = Blueprint('home', __name__)

@home.route('/home')
def index():
    return render_template('index.html')

@home.route('/cv')
def hojaVida():
    return render_template('principal.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    
    <link rel="stylesheet" href="/static/estilos.css">
</head>
<body>
    <header class="hero">
        <nav class="nav container">
            <div class="nav__logo">
                <h2 class="nav__title">Introducción a la Programación de Computadoras 2</h2>
            </div>
            <ul class="nav__link">
                <li class="nav__items">
                    <a href="{{url_for('home.hojaVida')}}" class="nav__links">Comenzar</a>
                </li>
                <img src="/static/img/arrow.svg" alt="close">
                <div class="nav__menu">
                </div>
            </ul>
        </nav>
        <section class="hero__container container">
            <h1 class="hero__title">Práctica 2</h1>
            <a href="{{url_for('home.hojaVida')}}" class="cta">Comenzar</a>
        </section>
    </header>
    <main>
        <section class="container about">
            <h2 class="subtitle">Información</h2>
            <div class="about__main">
                <article class="about__icons">
                    <img src="/static/img/user.svg" alt="user" class="about__icon">
                    <h3 class="about__title">Desarrollador</h3>
                    <p class="about__paragraph">Luis Daniel Salán Letona</p>
                </article>

                <article class="about__icons">
                    <img src="/static/img/user2.svg" alt="user" class="about__icon">
                    <h3 class="about__title">Auxiliar</h3>
                    <p class="about__paragraph">Daniel Alfaro Gaitán</p>
                </article>
            </div>
        </section>
    </main>
</body>
</html>

templates/principal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>CV LUIS SALÁN</title>
    <link rel="stylesheet" href="/static/principal.css">
</head>
<body>
    <section class="inicio" id="inicio">
        <div class="contenido-seccion">
            <header>
                <div class="nav-bar" onclick="mostrarOcultarMenu()">
                    <i class="fa-solid fa-bars"></i>
                </div>
                <nav id="nav" class="nav">
                    <a href="#home">Inicio</a>
                    <a href="#aboutme">Sobre mi</a>
                    <a href="#skills">Habilidades</a>
                    <a href="#resumen">Resumen</a>
                    <a href="#contact">Contacto</a>
                </nav>
                <div class="logo">
                    L<span class="color">S</span>
                </div>
            </header>
            <div class="info">
                <h1>LUIS SALÁN</h1>
                <h2>BACHILLER EN COMPUTACIÓN</h2>
                <div class="redes">
                    <a href="#"><i class="fa-brands fa-facebook"></i></a>
                    <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    <a href="#"><i class="fa-brands fa-whatsapp"></i></a>
                    <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                </div>
            </div>
            <div class="foto">
                <img src="/static/img/foto1.jpg" alt="mephoto">
            </div>
        </div>
    </section>
    <section class="sobremi" id="sobremi">
        <div class="contenido-seccion">
            <h2 class="titulo-seccion">Sobre Mi</h2>
            <h3>Detalles personales</h3>
            <p class="especial">Actualmente me dedico a estudiar en la 
                Universidad de San Carlos de Guatemala, especifícamente
                la carrera de Ingeniería en Ciencias y Sistemas.
            </p>
            <div class="fila">
                <div class="col">
                    <i class="fa-solid fa-user"></i>
                    <span class="titulo-detalle">Perfil</span>
                    <p>Apasionado a la tecnología, me
                        defino por ser una persona con
                        ganas de aprender y trabajar en
                        equipo, adaptándome a cualquier
                        ambiente.</p>
                </div>
                <div class="col">
                    <i class="fa-sharp fa-solid fa-location-dot"></i>
                    <span class="titulo-detalle">Ubicación</span>
                    <p>3ra. calle 1-81, Colonia Paraíso del Frutal Villa Nueva, zona 5</p>
                </div>
                <div class="col">
                    <i class="fa-solid fa-language"></i>
                    <span class="titulo-detalle">Idiomas</span>
                    <p>Español Nativo, Inglés Intermedio, Portugués Básico</p>
                </div>
            </div>
        </div>
    </section>
    <section class="habilidades" id="habilidades">
        <div class="contenido-seccion">
            <h2 class="titulo-seccion">Habilidades</h2>
            <h3>Tengo conocimientos en</h3>

            <div class="fila">
                <div class="col">
                    <span>SO Windows/Linux</span>
                    <div class="cont-barra">
                        <div class="barra" id="so">
                            <div class="e"></div>
                        </div>
                        <span>50%</span>
                    </div>
                </div>
                <div class="col">
                    <span>Java</span>
                    <div class="cont-barra">
                        <div class="barra" id="java">
                            <div class="e"></div>
                        </div>
                        <span>30%</span>
                    </div>
                </div>
            </div>
            <div class="fila">
                <div class="col">
                    <span>Python</span>
                    <div class="cont-barra">
                        <div class="barra" id="python">
                            <div class="e"></div>
                        </div>
                        <span>30%</span>
                    </div>
                </div>
                <div class="col">
                    <span>Mantenimiento de Equipo</span>
                    <div class="cont-barra">
                        <div class="barra" id="mantenimiento">
                            <div class="e"></div>
                        </div>
                        <span>80%</span>
                    </div>
                </div>
            </div>
            <div class="fila">
                <div class="col">
                    <span>Base de Datos</span>
                    <div class="cont-barra">
                        <div class="barra" id="database">
                            <div class="e"></div>
                        </div>
                        <span>30%</span>
                    </div>
                </div>
                <div class="col">
                    <span>Adobe Illustrator</span>
                    <div class="cont-barra">
                        <div class="barra" id="ai">
                            <div class="e"></div>
                        </div>
                        <span>50%</span>
                    </div>
                </div>
            </div>
            <div class="fila">
                <div class="col">
                    <span>Microsoft Office</span>
                    <div class="cont-barra">
                        <div class="barra" id="mo">
                            <div class="e"></div>
                        </div>
                        <span>50%</span>
                    </div>
                </div>
                <div class="col">
                    <span>Photoshop</span>
                    <div class="cont-barra">
                        <div class="barra" id="ps">
                            <div class="e"></div>
                        </div>
                        <span>40%</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <seccion class="resumen" id="resumen">
        <div class="contenido-seccion">
            <h2 class="titulo-seccion">Resumen</h2>
            <h3>Estudios y experiencia</h3>
            <div class="info">
                <div class="col">
                    <span class="titulo">Educación</span>
                    <table>
                        <tr>
                            <td class="datos">
                                <h3>Universidad de San Carlos de Guatemala</h3>
                            </td>
                            <td rowspan="2" class="descripcion">
                               Licenciatura en Ciencias y Sistemas 
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4>2020 - Actual.</h4>
                                <p>(7mo Semestre).</p>
                            </td>
                        </tr>
                        
                    </table>
                    <table>
                        <tr>
                            <td class="datos">
                                <h3>Universidad de San Carlos de Guatemala</h3>
                            </td>
                            <td rowspan="2" class="descripcion">
                               Inglés Técnico (nivel 12).
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4>2016 - 2022.</h4>
                                <p>CALUSAC</p>
                            </td>
                        </tr>
                        
                    </table>
                    <table>
                        <tr>
                            <td class="datos">
                                <h3>Colegio Valle Del Saber</h3>
                            </td>
                            <td rowspan="2" class="descripcion">
                               Diversificado
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4>2016 - 2018.</h4>
                                <p>Bachillerato en Computación con Orientación Cientifíca.</p>
                            </td>
                        </tr>
                        
                    </table>
                </div>
                <div class="col">
                    <span class="titulo">Experiencia Laboral</span>
                    <table>
                        <tr>
                            <td class="datos">
                                <h3>OVS Tienda de ropa (moda italiana)</h3>
                            </td>
                            <td rowspan="2" class="descripcion">
                               Auxiliar en Ventas (Vacacionista) 
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4>Diciembre 2018 - Diciembre 2018</h4>
                                <p>Servicio al cliente.</p>
                            </td>
                        </tr>
                        
                    </table>
                    <table>
                        <tr>
                            <td class="datos">
                                <h3>Gustavo Molina S.A.</h3>
                            </td>
                            <td rowspan="2" class="descripcion">
                               Prácticas supervisadas (No remunerado)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4>Septiembre 2018 - Octubre 2018</h4>
                                <p>Soporte Técnico.</p>
                            </td>
                        </tr>
                        
                    </table>
                </div>
            </div>
        </div>
    </seccion>
    <section class="contacto" id="contacto">
        <div class="contenido-seccion">
            <h2 class="titulo-seccion">Contacto</h2>
            <h3>Contactame ahora mismo!</h3>

            <div class="fila">
                <div class="col">
                    <h2>
                        <i class="fa-solid fa-phone"></i>Teléfono
                    </h2>
                    <span class="info-contacto">+502 4800-5262</span>
                </div>
                <div class="col">
                    <h2>
                        <i class="fa-solid fa-envelope"></i>E-mail
                    </h2>
                    <span class="info-contacto">luisdani405@gmail.com</span>
                </div>
                <div class="col">
                    <h2>
                        <i class="fa-solid fa-address-card"></i>DPI
                    </h2>
                    <span class="info-contacto">3007178220101</span>
                </div>
                <div class="col">
                    <h2>
                        <i class="fa-solid fa-image-polaroid-user"></i>NIT
                    </h2>
                    <span class="info-contacto">111944120</span>
                </div>
                
            </div>
        </div>
    </section>

    <script src="/static/app.js"></script>
</body>
</html>